version: "3.8"

services:
  jdownloader-parser-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jdownloader-parser-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
